name: Telegram Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram message
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${8507297777:AAEtUIWkh14gXLWUsoVNz2yEy2GfaRIzACY}/sendMessage" \
            -d "chat_id=${8842255539}" \
            --data-urlencode "text=🚨 PS5 Alarm funktioniert! 🎮"
